-- Active: 1653564627884@@127.0.0.1@3306@EjercicioFitnessgroup
CREATE TABLE SEDE(ID INT PRIMARY KEY AUTO_INCREMENT, DIRECCION VARCHAR(30), nombre varchar(20));
INSERT INTO SEDE(ID, DIRECCION, NOMBRE) VALUES (1, 'Botanico', 'SEDE_BOTANICO');

CREATE TABLE TIPO_CLASE(ID INT PRIMARY KEY, NOMBRE VARCHAR(20));
INSERT INTO TIPO_CLASE(ID, NOMBRE) VALUES (1, 'YOGA');

CREATE TABLE CLASES(ID INT PRIMARY KEY, NOMBRE VARCHAR(30), DURACION VARCHAR(30), ID_SEDE INT, ID_TIPO_CLASE INT,
 CONSTRAINT FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID), CONSTRAINT FOREIGN KEY (ID_TIPO_CLASE) REFERENCES TIPO_CLASE(ID));

INSERT INTO CLASES (ID, NOMBRE, DURACION, ID_SEDE, ID_TIPO_CLASE) VALUES (1,'CLASE1', '60MINUTOS', 1, 1);

CREATE TABLE USUARIO (DOCUMENTO BIGINT PRIMARY KEY , NOMBRE VARCHAR(20), EDAD INT, APELLIDO VARCHAR(20));
INSERT INTO USUARIO (DOCUMENTO, NOMBRE, EDAD, APELLIDO) VALUES (45833453, 'TADEO', 18, 'FUNES');

CREATE TABLE RESERVA_USUARIO (ID INT PRIMARY KEY AUTO_INCREMENT, ID_CLASE INT, DOCUMENTO BIGINT, CONSTRAINT FOREIGN KEY (DOCUMENTO) REFERENCES USUARIO(DOCUMENTO));
INSERT INTO RESERVA_USUARIO (ID,ID_CLASE, DOCUMENTO) VALUES (1, 1, 45833453);

CREATE TABLE ASISTENCIA(ID INT PRIMARY KEY, ESTADO VARCHAR(20), ID_RESERVA INT, CONSTRAINT FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA_USUARIO(ID));

INSERT INTO ASISTENCIA(ID , ESTADO, ID_RESERVA) VALUES (1, 'ACTIVO', 1);

CREATE TABLE PLAN(ID INT PRIMARY KEY AUTO_INCREMENT, DOCUMENTO_USUARIO BIGINT, CONSTRAINT FOREIGN KEY (DOCUMENTO_USUARIO) REFERENCES USUARIO(DOCUMENTO));

INSERT INTO PLAN (ID, DOCUMENTO_USUARIO) VALUES (1, 45833453);

CREATE TABLE SESION 


